source 'https://ruby.taobao.org'

gem 'rake'

# jekyll, which builds it all
# 2.0 includes sass processing
gem 'jekyll', '~>2.0'

# Auto redirect pages
gem 'jekyll-redirect-from'

# JSON
gem 'json'

# For `rake watch`
gem 'rb-fsevent'

# For markdown header cleanup
gem 'sanitize', '~>2.0'

# For frontend search
gem 'jekyll-lunr-js-search', :git => "https://github.com/masterfix/jekyll-lunr-js-search.git"
